CREATE SCHEMA srDB;

CREATE TABLE USERS(
userID INT (2) NOT NULL AUTO_INCREMENT,
fName VARCHAR (20),
userEmail VARCHAR (50),
mobileNo INT (10),
userName VARCHAR (20),
Pass VARCHAR (20),
CONSTRAINT userID_PK PRIMARY KEY (userID)
);

CREATE TABLE CARTS(
cartNumber INT (5) NOT NULL AUTO_INCREMENT,
userID INT (2) NOT NULL,
address TEXT (90000),
orders TEXT (9000),
PRIMARY KEY(cartNumber,userID),
FOREIGN KEY (userID) REFERENCES USERS(userID) 
);
